# Regenerates sitemap.xml (and robots.txt) from the pages actually on disk.
#
# Run this whenever you ADD or REMOVE a page:
#     Windows:      powershell -ExecutionPolicy Bypass -File tools\generate-sitemap.ps1
#     Ubuntu/macOS: pwsh -File tools/generate-sitemap.ps1
#
# Every .html file is listed except the ones in $exclude below. `lastmod`
# comes from each file's modification time - Google uses it to decide what
# is worth re-crawling, so it is only useful while it stays honest.
#
# changefreq and priority are deliberately omitted: Google has stated it
# ignores both, and writing them just creates something else to go stale.

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$site = 'https://nhannhuthung.github.io'

# Pages that should not appear in search results.
$exclude = @(
    'google*.html'    # Search Console ownership token, not content
)

# index.html is served at the bare domain, and that is what its canonical
# tag claims, so list it that way rather than as /index.html.
$homePage = 'index.html'

function Should-Exclude([string]$relative) {
    foreach ($pattern in $exclude) {
        if ((Split-Path $relative -Leaf) -like $pattern) { return $true }
    }
    return $false
}

$entries = @()
foreach ($f in (Get-ChildItem -Path $repo -Filter *.html -Recurse | Sort-Object FullName)) {
    $rel = $f.FullName.Substring($repo.Length + 1) -replace '\\', '/'
    if (Should-Exclude $rel) { continue }

    $loc = if ($rel -eq $homePage) { "$site/" } else { "$site/$rel" }
    $entries += [pscustomobject]@{
        loc     = $loc
        lastmod = $f.LastWriteTime.ToString('yyyy-MM-dd')
    }
}

# the home page first, then everything else alphabetically
$entries = @($entries | Where-Object { $_.loc -eq "$site/" }) +
           @($entries | Where-Object { $_.loc -ne "$site/" } | Sort-Object loc)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
[void]$sb.AppendLine('<!-- AUTO-GENERATED by tools/generate-sitemap.ps1 - do not edit by hand. -->')
[void]$sb.AppendLine('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
foreach ($e in $entries) {
    [void]$sb.AppendLine('  <url>')
    [void]$sb.AppendLine("    <loc>$([System.Security.SecurityElement]::Escape($e.loc))</loc>")
    [void]$sb.AppendLine("    <lastmod>$($e.lastmod)</lastmod>")
    [void]$sb.AppendLine('  </url>')
}
[void]$sb.AppendLine('</urlset>')

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText((Join-Path $repo 'sitemap.xml'), $sb.ToString(), $utf8NoBom)

# robots.txt: allow everything, and point crawlers at the sitemap. Nothing
# here is private, and a stray Disallow would also hide the verification
# file and the favicon - which would quietly break both.
$robots = @"
# Everything on this site is public.
User-agent: *
Allow: /

Sitemap: $site/sitemap.xml
"@
[IO.File]::WriteAllText((Join-Path $repo 'robots.txt'), $robots, $utf8NoBom)

""
"Wrote sitemap.xml with $($entries.Count) URLs."
"Wrote robots.txt pointing at $site/sitemap.xml"
$skipped = (Get-ChildItem -Path $repo -Filter *.html -Recurse).Count - $entries.Count
if ($skipped -gt 0) { "Excluded $skipped file(s): $($exclude -join ', ')" }
